seed : 5
data_path : '/home/yishido/DATA/imagenet'
image_size : 224
mean : [0.485, 0.456, 0.406]
std : [0.229, 0.224, 0.225]
batch_size : 64
num_workers : 10
epoch : 100
optimizer : 'adamw'
lr : 0
momentum : 0.9
model : 'vit_tiny_patch16_224'
num_class : 1000
step_size : 30
gamma : 0.1
save_epoch : 10
save_path : './output'